python3-tensorflow-lite: Remove execstack bit from the interpreter wrapper lib
This fixes the runtime error when importing tflite_runtime.interpreter:

Traceback (most recent call last):
  File "/usr/share/tensorflow/lite/examples/python/label_image.py", line 22, in <module>
    import tflite_runtime.interpreter as tflite
  File "/usr/lib/python3.13/site-packages/tflite_runtime/interpreter.py", line 34, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /usr/lib/python3.13/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so: cannot enable executable stack as shared object requires: Invalid argument

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>